name: Update playlist

on:
  workflow_dispatch:
  schedule:
    - cron: '15 3 * * 1'

jobs:
  run_script:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-r
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1.0'
      
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev

      # - name: Cache packages
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.local/share/renv
      #     key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-renv-
      # 
      # - name: Install Package Dependencies
      #   run: |-
      #     Rscript -e "install.packages('renv'); renv::restore(confirm = FALSE)"

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('dplyr', 'purrr', 'spotifyr', 'glue', 'stringdist', 'remotes', 'gt', 'lubridate', 'rmarkdown', 'knitr'))"

      - name: Install rozhlas packages
        run: |-
          Rscript -e "remotes::install_github('skvrnami/rozhlas')"
      
      - name: Knit playlist
        env: 
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
        run: |- 
          Rscript -e "rmarkdown::render('fully-automated-playlist/playlist.Rmd', output_file = 'index.html')"
      
        
      - name: Commit and push
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "Update playlist" || exit 0
          git push
